# Generated by Django 3.0.1 on 2019-12-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20191228_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinfo',
            name='expense_name',
            field=models.CharField(max_length=20),
        ),
    ]
